CC = gcc -Wall
CFLAGS = -c
TARGET = aaa
OBJS = main.o add.o 
CC := $(CC) -g
TARGET : $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

main.o : main.c
	$(CC) $(CFLAGS) main.c

add.o : add.c
	$(CC) $(CFLAGS) add.c
